version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      PGUSER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  flway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/mydatabase -user=postgres -password=password migrate
    volumes:
      - ./src/main/resources/sql/:/flyway/sql/
    depends_on:
      postgres:
        condition: service_healthy
